# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PreviewFore": "00_core.ipynb",
         "SyntheticImageBuild": "00_core.ipynb",
         "UtilsBuildLinearCoord": "01_utils.ipynb",
         "openImg": "02_display.ipynb",
         "imageSize": "02_display.ipynb",
         "displayImage": "02_display.ipynb",
         "displayTarBarImage": "02_display.ipynb",
         "displayGridRandom": "02_display.ipynb",
         "mkDir": "03_dirView.ipynb",
         "additionalMssg": "03_dirView.ipynb",
         "fileCount": "03_dirView.ipynb",
         "listFile": "03_dirView.ipynb",
         "itemize": "03_dirView.ipynb",
         "rmFile": "03_dirView.ipynb",
         "rmFileExt": "03_dirView.ipynb",
         "rmDir": "03_dirView.ipynb",
         "showDirInf": "03_dirView.ipynb",
         "randomCoordinates": "04_generate_coordinate.ipynb",
         "generateRandCoord": "04_generate_coordinate.ipynb"}

modules = ["core.py",
           "utils.py",
           "display.py",
           "dirView.py",
           "generate_coordinate.py"]

doc_url = "https://chho-work.github.io/syntheticReplica/"

git_url = "https://github.com/chho-work/syntheticReplica/tree/master/"

def custom_doc_links(name): return None
