# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PreviewFore": "00_core.ipynb",
         "SyntheticImageBuild": "00_core.ipynb",
         "UtilsBuildLinearCoord": "01_utils.ipynb",
         "openImg": "02_display.ipynb",
         "imageSize": "02_display.ipynb",
         "displayImage": "02_display.ipynb",
         "displayTarBarImage": "02_display.ipynb",
         "displayGridRandom": "02_display.ipynb"}

modules = ["core.py",
           "utils.py",
           "display.py",
           "dirView.py"]

doc_url = "https://chho-work.github.io/syntheticReplica/"

git_url = "https://github.com/chho-work/syntheticReplica/tree/master/"

def custom_doc_links(name): return None
