# AUTOGENERATED! DO NOT EDIT! File to edit: 01_utils.ipynb (unless otherwise specified).

__all__ = ['UtilsBuildLinearCoord']

# Cell

import pandas as pd
from PIL import Image

class UtilsBuildLinearCoord:
    # Plot horizontal(X-Axis) or vertical(Y-Axis) lines for a specific range of coordinates.
    # Todo: add more axis(as option)
    @staticmethod
    def buildAnnotPoint(init_pto:list, expand_x:int, expand_y:int) -> int:
        x_pto = [init_pto[0] + expand_x, init_pto[1]]
        y_pto = [init_pto[0], init_pto[1] + expand_y]
        return x_pto, y_pto

    @staticmethod
    def convertMatplot(init_pto:list, x_pto, y_pto):
        for i1, i2, i3 in zip(init_pto, x_pto, y_pto):
            yield [i1, i2]
            yield [i1, i3]

    @staticmethod
    def storeXY(generate) -> list:
        store = []
        while True:
            try:
                # Get next value from Generator object
                num = next(generate)
                store.append(num)
            except StopIteration:
                break
        return store

    # Convert column to list
    @staticmethod
    def col2List(path_csv:str) -> list:
        df_col2List = pd.read_csv(path_csv, index_col=0)
        col_init_pto = df_col2List.reset_index()[['init_pto_x', 'init_pto_y']].values.tolist()
        col_expand_x = df_col2List['expand_x'].tolist()
        col_expand_y = df_col2List['expand_y'].tolist()
        return col_init_pto, col_expand_x, col_expand_y

    @staticmethod
    def openImg(path_image:str):
        return Image.open(path_image)